[[redirects]]
  from = "/course/syllabus/teamwork/*"
  to = "/course/syllabus/foundation/teamwork/:splat/"

[[redirects]]
  from = "/course/syllabus/http/*"
  to = "/course/syllabus/foundation/http/:splat/"

[[redirects]]
  from = "/course/syllabus/testing/*"
  to = "/course/syllabus/foundation/testing/:splat/"

[[redirects]]
  from = "/course/syllabus/:topic/:section"
  to = "/course/syllabus/developer/:topic/:section/"